### ISSUE TITLE
Loader tool: Selection changes upon just hover over Version Column

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-core#1007]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior:

Currently when hovering over ```Version``` column user selection will change without even clicking other product.

As below:

![Image](https://github.com/user-attachments/assets/2a23bf8a-6ed2-49d4-b6cb-6205ec8ddd5f)

### Expected Behavior:

The selection shouldnt change without user clicking any other product(s) but stay as is.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1) Open Loader and select some product via left click
2) Hover over ```Version``` column to other product
3) Selection from step 1) will change without users will

### Are there any labels you wish to add?

- [x] I have added the relevant labels to the bug report.

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
I can't reproduce this on my end. Is this tray loader, or within a certain host?

**Comment by LiborBatek** [comment]
> I can't reproduce this on my end. Is this tray loader, or within a certain host?
> 
> It does do it for me if I keep middle mouse selected when hovering it though.

been experienced in ```blender``` and ```UE```....

**Comment by iLLiCiTiT** [comment]
I did replicate it in tray loader, in maya and in nuke.
