### ISSUE TITLE
Bug: Timeline reset doesn't work expected in 3dmax when reset frame range is performed

### ISSUE THREAD

**Issue by moonyuet** [ynput/ayon-core#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When accessing the AYON menu and clicking `Set Frame Range`, it only sets the frame ranges in render settings correctly while it doesn't set timeline accordingly to the database.
As it doesn't perform correctly, the repair action of the validator to check on frame range is broken and can't reset the frame range as expected.
The excerpt shows the errors after using repair action in validate frame range. 
```
DEBUG:pyblish.pyblish.plugin.Action:Finding failed instances..
DEBUG:pyblish.pyblish.plugin.Action:Attempting repair for instance: pointcacheMain ...
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
DEBUG:pyblish.pyblish.plugin.Action:Attempting repair for instance: reviewMain ...
DEBUG:GlobalServerAPI:Response <RestApiResponse [200]>
```

### Expected Behavior:

It should set the correct frame ranges in render settings and timeline.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

Set Frame Range
1. Launch Max via AYON
2. Go to AYON menu
3. Click `Set Frame Range`
4. It sets the frame range in render setting correctly but not the timeline

Validate Frame Range
1. Create pointcache/render/tycache/review instance
2. Make sure `Validate Frame Range` turning on 
3. When performing validation and the frame range in the scene doesn't match with the DB, it will error out
4. Use repair action to fix but fails to fix the frame range

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-8383](https://app.clickup.com/t/86bxnbxn5)]

**Comment by LiborBatek** [comment]
Is working in the latest develop.
