### ISSUE TITLE
Enhancement: Filtering shown creator plugins based on preset / settings profile

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-core#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

For certain workflows and pipeline steps, it would be easier to limit number of creators presented in Publisher UI. For example, modeler willl probably never need to publish VDBs, etc. This is highly workflow specific so it needs to be customizable by the studio itself.

### How would you imagine the implementation of the feature?

There are two ways (or more):

**Preset**
Define sets of creators in lists and show those list as preset selector in the Publisher

**Profiles**
Define list of creators per host on project level with set of task type/task name/asset or even user role?

All of it needs button in publisher to ignore and show all anyway.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-2539](https://app.clickup.com/t/86bxp3p06)]

**Comment by BigRoy** [comment]
I believe this was implemented by @kalisp with https://github.com/ynput/ayon-core/pull/560

The setting is: `ayon+settings://core/tools/creator/filter_creator_profiles`
