### ISSUE TITLE
Houdini: Instance in current context validator

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-core#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

We are missing the same validator that was already made for Maya and Max (#58).

### How would you imagine the implementation of the feature?

It should have the same functionality - optional validator that can be disabled per host/task type (to allow easy mutli-shot workflows) with repair action that will set the context to the current one. 

> [!NOTE]
> Some of it is touched by OpenPype PR ynput/openpype#6207.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-3641](https://app.clickup.com/t/86bxu6kmx)]

**Comment by BigRoy** [comment]
We have this implemented I believe, see [here](https://github.com/BigRoy/OpenPype/blob/b4d5a7465e95992e1ae07894f62e189e3559b67d/openpype/hosts/houdini/plugins/publish/validate_instance_in_context.py).
