### ISSUE TITLE
Drop explicit product type list from integrator

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-core#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

CUrrently, we have explicit list of product types (families) defined in `integrate.py` global integrator that is limiting on what instances this integrator runs. If you add your new product type no matter how simple it is, you need to change code in `ayon-core` to integrate it.

### How would you imagine the implementation of the feature?

We should drop this list completely and use `integrate = True/False` on instance to determine if it should be integrated or not to unbind it from the host specific and workflow specific definitions. This needs to be done before we split to multiple repositories otherwise any addition to host addon will need also change in `ayon-core`.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

We could add that list to Settings but then we just change the place where we maintain list of product types.

[cuID:[AY-4138](https://app.clickup.com/t/86by22b62)]

**Comment by BigRoy** [comment]
> We could add that list to Settings but then we just change the place where we maintain list of product types.

Plus that it's much harder for studios to keep this synced to future updates - because they might already have their own overrides on top of the defaults. Not sure if that's a good workflow.
