### ISSUE TITLE
Houdini: Load Alembic - disable automatic unpacking

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Loading an Alembic into Houdini via the loader [automatically adds an "Unpack" and "Normal" node](https://github.com/ynput/ayon-core/blob/5db37c9590174fd913a51fc006102c32d374076a/client/ayon_core/hosts/houdini/plugins/load/load_alembic.py#L47-L66) which a long time ago was added for ease of access to the data (by artists at our studio).

However, @fabiaserra [stated here](https://github.com/ynput/ayon-core/pull/227#discussion_r1539019570) that it might not be a good idea to keep that around and instead rely on automating less and instead leave it up to Houdini artists to manage the data. In essence, not creating those additional nodes on load.

### How would you imagine the implementation of the feature?

Since it has been there for so long we might want to consider backwards compatibility. Just removing the logic for creation of those nodes should still work fine with existing loaded entries (they will just keep the nodes around) so it should be trivial to be 'forward' compatible.

The real question becomes, do we ever still want to _keep_ the logic that it automatically creates it for you.

We could add it as "Options" on the Loader (little option box on the loader) or could make it a Project Settings to enable/disable the logic.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-4796](https://app.clickup.com/t/86by894ge)]

**Comment by BigRoy** [comment]
Just adding @fabiaserra 's comment from [here](https://github.com/ynput/ayon-core/pull/227#discussion_r1539035638):

> anyway, I didn't mean to go in a tangent as this PR sorts out a very specific case and it should be merged but it caught my attention. In the future I think that should be an exposed option on the loader that artists can easily control during the load action, and since I'm already going in a big tangent... not sure if we ended up creating a discussion to refactor the loader UX? I think it should be much easier to visualize the control of how things are loaded in a friendlier way than the current options dialog that's hidden on the action menu and you need to do extra clicks. Thinking for example on the ftrack loader https://www.ftrack.com/wp-content/uploads/2021/04/ftrack-Studio-Houdini-%E2%80%93-import-alembic-jpg-1536x840.jpg (even though there's no exposed options in this example) but that's where you'd control whether the representation gets loaded as archive, packed, unpacked, assign materials.... (and you can leave it by default if you don't care) and not the current approach of having an action menu for each permutation of load plugin and representation

**Comment by MustafaJafar** [comment]
> not sure if we ended up creating a discussion to refactor the loader UX? 

As far as I know, the loader UX is the same across all Hosts. which _I assume_ makes it hard to add customizations per Host ?

**Comment by fabiaserra** [comment]
> > not sure if we ended up creating a discussion to refactor the loader UX?
> 
> As far as I know, the loader UX is the same across all Hosts. which _I assume_ makes it hard to add customizations per Host ?

what I'm suggesting is not specific to Houdini, the same issue is present on all hosts

**Comment by BigRoy** [comment]
> I personally think that's too much exposed control without little benefit and quite unintuitive for the Ayon/OP admin, I'd rather be a bit more opinionated on the different possible efficient workflows through exposed options than leaving it open like this. I think I'd rather have a generic SOP HDA (like the LOP Ayon Load one that I've seen from @BigRoy) that can load any geo representation and has exposed options to control the internal graph of how to load it than having a tree of vanilla nodes.

Just wanted to add that I agree. I wouldn't want to make up a new 'structure' based on JSON or whatever - it's just too limiting and too hard to set up as well.

If someone wants a custom loader - they surely can, and it's really not that hard to implement. However, what AYON offers out of the box should be simple and _not too specific_ to a certain way or working. So for now - I think removing the `unpack`, `normal` and `null` is a good thing to do. Basically it doesn't hold anyone from still doing it themselves if they do want to customize it - but it's just an odd default since you definitely don't want to _always_ unpack things, etc.
