### ISSUE TITLE
Resolve Clip Load - Slate support

### ISSUE THREAD

**Issue by tokejepsen** [ynput/ayon-core#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Missing port of https://github.com/ynput/OpenPype/pull/6126

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

See original PR

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
The logic the mentioned PR changes seems to be present in `ayon-resolve` currently, so I'll close this.
