### ISSUE TITLE
Maya: Rendering multilayer EXR images always resulting into names with "_beauty" suffix

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-core#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

When rendering from ```maya``` host in Deadline and having set ```merge AOVs``` option leading to single image file containing all AOVs  results into rendered image with ```<filename>_beauty.exr``` even tho there is no reason to append the ```_beauty``` suffix as it contains all RGBA data not just beauty component.

Currently there is now way to produce renders without ```_beauty``` suffix for multilayer EXR.

Here are staged files when rendering (all seems normal):

![Screenshot 2024-04-22 135914](https://github.com/ynput/ayon-core/assets/112623825/f00515f6-677d-46d7-a0a7-b68b22e5c05d)

And when rendered and published (containing the "_beauty" suffix which cant be turned off)

![Screenshot 2024-04-22 140357](https://github.com/ynput/ayon-core/assets/112623825/604d927b-26cf-4749-af02-7dd005fcbe6b)

### How would you imagine the implementation of the feature?

When rendering into multilayer EXR containing all AOVs (merged) there should not be appended ```_beauty``` suffix at all. But only when multiple files being produced and such file might contain just the beauty component.

There should be ```Template naming``` used for such a task as now it is not ...being somewhat hardcoded as seen [here](https://github.com/ynput/ayon-core/blob/15d16198e56848b57a8ceca9b7f3c93f46e3d6c7/client/ayon_core/pipeline/farm/pyblish_functions.py#L555-L630)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by LiborBatek** [comment]
Maybe solved by this [PR](https://github.com/ynput/ayon-core/pull/447)

**Comment by BigRoy** [comment]
@LiborBatek is this still present for Maya? If so, should this move to the `ayon-maya` repo?

**Comment by LiborBatek** [comment]
@BigRoy it should be already resolved by using Publish Templates with <AOV> token ...can be closed IMHO

**Comment by BigRoy** [comment]
Thanks. Feel free to re-open on `ayon-maya` if you find new issues.

> resolved by using Publish Templates 

If there were specific changes need in settings for this it may be good to mention the required changes here so we have it as a reference for the backlog.
