### ISSUE TITLE
{parent} bug in Workfiles tool

### ISSUE THREAD

**Issue by DF-Huan** [ynput/ayon-core#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I set the Anatomy template with `{parent}` key in the **Directory template** and **File name template**, but **Workfiles tool** can't solve the `{parent}` key.

Test in Houdini and Maya.

here's the snapshots:
![image](https://github.com/ynput/ayon-core/assets/100280100/0f02a9ef-1c48-4115-ac53-898ff2493f62)
![image](https://github.com/ynput/ayon-core/assets/100280100/76b42263-6e42-49d5-b5fc-e8159a1ba57e)
![image](https://github.com/ynput/ayon-core/assets/100280100/85835e10-7ee7-454c-b6da-a3d4d7188177)

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Set Anatomy template with {parent} string.
2. Open Workfiles tool in DCCs.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by iLLiCiTiT** [comment]
Is this still relevant issue?

**Comment by DF-Huan** [comment]
Tested with AYON server 1.5.1+202410141209 and AYON launcher 1.1.1, the issue has been resolved.
