### ISSUE TITLE
Publish existing BGEO.sc, vdb, abc cache in Houdini

### ISSUE THREAD

**Issue by krishna8008** [ynput/ayon-core#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

To publish the existing caches in houdini, there should be a publish existing frames option available, just like arnold,karma..etc

### How would you imagine the implementation of the feature?

This works almost same publishing existing frames in arnold,karma,etc but here its caches like BGEO,VDB,ABC

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-5337](https://app.clickup.com/t/86byr954q)]

**Comment by MustafaJafar** [comment]
Thanks for creating this issue. 
I've added it to our backlog. 

> [!NOTE]
> This request is similar to https://github.com/ynput/ayon-core/pull/328 but for Bgeo, vdb and similar product types.
