### ISSUE TITLE
Houdini: Publish different HDA products from different folder paths with the same product name

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-core#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When creating different HDAs in AYON that have the same product name.
HDA creator by default will create all of them with the same Houdini asset name. 

The problem occurs when loading these different HDAs where AYON will think they are different but Houdini will think they are the same.
In this screenshot, I have loaded two products with the same product name `hdaMain` that were published from two different folder paths and as mentioned Houdini consider them the same HDA.
![image](https://github.com/ynput/ayon-core/assets/20871534/de3b0c4b-6723-40ee-95b4-b9fc3b6f793b)

### Expected Behavior:

These HDAs should be mixed up. 

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. publish two HDAs from two different folder paths with the same variant name.
2. Load both of these HDAs in another folder path.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by AlSzab** [comment]
Seem like the operator type/Asset Name gets created via {product_type}{variant} in the houdini Creator (probably somewhere here: https://github.com/ynput/ayon-core/blob/aa1ac9762a3af22fec14c4e0932a80cfdcbc426a/client/ayon_core/hosts/houdini/api/plugin.py#L172) 
instead I think we might need the actual asset name as operator type
