### ISSUE TITLE
Substance Painter: Changing the type of verbosity when creating  thumbnails from non-color image products

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-core#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

ATM when publishing ```texture set``` consisting of multiple ```products``` user gets false warning upon publishing that ```oiiotool``` failed to create thumbnail for products without ```RGBA``` channels present.

But in reality the ```thumbnail``` is created via ```ffmpg``` tool so in the end the publish being succesful on all fronts, so no need to show off such ```Failure Warnings``` imho. 

![Screenshot 2024-05-23 170818](https://github.com/ynput/ayon-core/assets/112623825/0595ceb0-e7fd-44bb-9d7f-e71e5750cee6)

### How would you imagine the implementation of the feature?

Ideally all green signed publishing without unnecessary warnings of this type when the publishing ending up correct.

We should change the level of notification that ```oiiotool``` not been involved in creation of ```thumbnails```

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
If still relevant @LiborBatek could you transfer this issue to [`ayon-substance-painter`](https://github.com/ynput/ayon-substance-painter)?

**Comment by LiborBatek** [comment]
Could be closed as it has been moved to substance repository [https://github.com/ynput/ayon-substance-painter/issues/1](url)

**Comment by BigRoy** [comment]
@LiborBatek just wanted to remark that you can **Transfer** the issue itself from here to there. The good thing is:

- History is preserved with comments.
- It's gone from ayon-core, and directly available on ayon-substance-painter
- You don't need to manually recreate it.

It should be right hand side on Github.

See e.g. screenshot:
![image](https://github.com/ynput/ayon-core/assets/2439881/4cd6de92-a860-4e87-a47e-384ce459adb6)
