### ISSUE TITLE
Publish Reviews & Thumbnails

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-core#584]
As an Maya Artist, when I publish a product and want to create review or thumbnail representation, I should be able to request and configure it in one place (probably the Publisher UI)

**Comment by BigRoy** [comment]
Could you elaborate on what is lacking from the current configurability?

- Currently Maya publishes can create 'review' which are playblasts of the scene that also generate thumbnails on publish.
- Maya also published the workfile with a screengrab from an active viewport (if any)
- And in the publisher UI you can also, in all hosts, add a thumbnail yourself to an instance via the thumbnail widget top right.

**Comment by dee-ynput** [comment]
This came out a long time ago in a discussion with @antirotor. I believe it was in the context of the extending the publisher for your USD workflow (not 100% sure though 😅)

I jotted this in a draft issue at the time to be remainded later and not forget about it.
It surfaces now because that draft has been turned into an issue.
So being reminded is achieved 👍 
But not forgetting is not a success for me 👎 😅 

Does it ring a bell on your side @antirotor ? 🙏

**Comment by BigRoy** [comment]
Pinging @antirotor ? Any chance this is relevant or could/should be closed? (or even get moved to `ayon-maya`?)

**Comment by BigRoy** [comment]
We did hit an issue _just now_ that when an artist manually adds a thumbnail in the Publisher UI whilst publishing a review that you get an error on Integration. I wonder if this issue was basically meant to represent that issue.

```python
Detail: duplicate key value violates unique constraint "representation_unique_name_on_version"
DETAIL:  Key (version_id, name)=(02095dc2-3eab-11ef-9ab2-6cb3114ff9ea, thumbnail) already exists..

Traceback (most recent call last):
  File "C:\Users\Maqina-02\AppData\Local\Ynput\AYON\dependency_packages\ayon_2404022047_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\Maqina-02\AppData\Local\Ynput\AYON\addons\core_0.4.1-dev.1\ayon_core\plugins\publish\integrate.py", line 171, in process
    six.reraise(*sys.exc_info())
  File "C:\Program Files\Ynput\AYON 1.0.3-dev.1\dependencies\six.py", line 719, in reraise
    raise value
  File "C:\Users\Maqina-02\AppData\Local\Ynput\AYON\addons\core_0.4.1-dev.1\ayon_core\plugins\publish\integrate.py", line 158, in process
    self.register(instance, file_transactions, filtered_repres)
  File "C:\Users\Maqina-02\AppData\Local\Ynput\AYON\addons\core_0.4.1-dev.1\ayon_core\plugins\publish\integrate.py", line 351, in register
    op_session.commit()
  File "C:\Program Files\Ynput\AYON 1.0.3-dev.1\dependencies\ayon_api\operations.py", line 701, in commit
    self._con.send_batch_operations(
  File "C:\Program Files\Ynput\AYON 1.0.3-dev.1\dependencies\ayon_api\server_api.py", line 6575, in send_batch_operations
    raise FailedOperations((
ayon_api.exceptions.FailedOperations: Operation "30cf66d7-a46d-409d-9fff-6c91410617be" failed with data:
{
   ... removed due to confidential data ...
}
Detail: duplicate key value violates unique constraint "representation_unique_name_on_version"
DETAIL:  Key (version_id, name)=(02095dc2-3eab-11ef-9ab2-6cb3114ff9ea, thumbnail) already exists..
```

**Comment by BigRoy** [comment]
Should we transfer this issue to `ayon-maya` if it's still a relevant issue?

**Comment by antirotor** [comment]
sorry, I finally found this place, thanks @BigRoy 

So if I am not mistaken this was more generic stuff than Maya specific and it comes from the discussions I had with various artist. It goes like that (and if this is so @dee-ynput, let's rename the issue and modify description :)):

Sometimes artists find simple task of creating reviewables and/or thumbnails difficult. Current approach we have provides lot of customization and freedom to tweak: creating review instance with it's own set of plugins and plugin attributes and settings. We've added ability to create snapshots for thumbnails and that is on the other side of things of simplicity and that is all fine.

But artists usually expect that there should be simple way of creating reviews, just with the checkbox on publishing instance (or some other control that could act as visual identificator that particular instance will produce reviewable)

![image](https://github.com/ynput/ayon-core/assets/33513211/55fc14c3-f0f4-4eb5-9cfd-1623f69dc65b)

Like in this case, there could be "toggable something" next to the modelMain in the item field that will visually represent that this will produce reviewable and based on the context, clicking on with would allow you to select camera for example (but that's host specific behaviour).

Overall this stems from the fact, that in most cases you should be able to produce reviewable video with as few clicks as possible. This can be achieved by other means and this issue should serve as discussion place for streamlining this.

**Comment by BigRoy** [comment]
I see - not commenting on the review functionality specifically. 

But design-wise I'd say that if we want custom special behavior for instances on these cards that we can basically add `Creator.actions`  similar to what Pyblish Plug-in actions do to support custom actions for plug-ins.

So that if a Creator defines actions, one could e.g. right click the Card and pick one of the actions. When doing so, that could e.g. also easily offer functionality in hosts like "Select instance node", "Set extract review export settings from current view", etc.

These options could also show on the "Publish" tab for the Creator so that they are also more visible than just the context menu - similar to how in a publish report the actions are presented to the user.

The nice thing about this - it's easily extendable. It _can_ implement host-specific functionality.
There is a downside however, is that one couldn't easily expand the actions available for a Creator or alike from e.g. a studio-specific addon because the actions are defined on the Creator class itself.

**Comment by dee-ynput** [comment]
closing: undefined, duplicate.
