### ISSUE TITLE
Ayon Core: Review movie not created / integrated during Publishing (latest develop)

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-core#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When publishing ```Review``` product its missing in the publish folder. There is only present ```Thumbnail``` product.

This has been experienced when publishing from ```Maya``` and ```SubstancePainter``` hosts, possibly also from ```AE``` host.

There are also no uploaded ```thumbnails``` on AYON server when inspected the products the ```review``` was made for.

Here is a full JSON publish report:

[publish-report-240605-10-37.json.txt](https://github.com/user-attachments/files/15581238/publish-report-240605-10-37.json.txt)

![image](https://github.com/ynput/ayon-core/assets/112623825/0704610a-1dd4-4704-85a5-ba621f354b98)

### Expected Behavior:

The ```Review``` publishing should output movie (mp4) as reviewable always. Now just ```thumbnail``` is produced after publish.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create ```Review``` publish instance
2. Publish it
3. Inspect output publish folder if mp4 file present

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[AY-5723](https://app.clickup.com/t/86bz2qj9a)]

**Comment by BigRoy** [comment]
@LiborBatek could you provide more details?

This seems to work fine from Maya for me:

![image](https://github.com/ynput/ayon-core/assets/2439881/d9ce67cf-a287-43f3-8fa0-6de9bbfa5062)

Both with global color management enabled or disabled in the project.
Maybe you have some problematic overrides in settings in any of:

- `ayon+settings://core/imageio`
- `ayon+settings://core/publish/ExtractOIIOTranscode/profiles`
- `ayon+settings://core/publish/ExtractReview`
- `ayon+settings://core/publish/ExtractBurnin`

**Comment by LiborBatek** [comment]
@BigRoy  it seems its tied to ```oiio transcode``` if disabled all works fine...

We can close this one as there is already PR for that...

[https://github.com/ynput/ayon-core/pull/620#event-13101400881](url)
