### ISSUE TITLE
Chore: Issue with version up function

### ISSUE THREAD

**Issue by moonyuet** [ynput/ayon-core#596]
As said before - this check does not fix things. See [here](https://github.com/ynput/ayon-core/pull/545#discussion_r1627782264) - it's redundant code.

However, the issue presented [here](https://github.com/ynput/ayon-core/pull/545#discussion_r1627697790) I assume is still present? (Or I might be misinterpreting the code and it's not an issue at all; worth a test run I suppose?)

_Originally posted by @BigRoy in https://github.com/ynput/ayon-core/pull/545#discussion_r1627887519_

**Comment by BigRoy** [comment]
Thanks - will take a look at this hopefully next week.

**Comment by BigRoy** [comment]
I tested the version up logic in Maya and it does seem to increment beyond gaps so it seems to work without any issue.
