### ISSUE TITLE
Remove deprecated `ocio_config` `ImageIOConfigModel` settings for each addon

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently the settings for `ayon-houdini` contains a deprecated [`ImageIOConfigModel`](https://github.com/ynput/ayon-houdini/blob/20a0273b61bd491ca173896c89a9fce1c28cdd75/server/settings/imageio.py#L6-L29).

With [the support of profiles to determine OCIO config in ayon-core](https://github.com/ynput/ayon-core/pull/490) this logic has been superseded and should be removed from each addon still having the deprecated settings.

### How would you imagine the implementation of the feature?

Remove the deprecated settings, and ensure transition for existing users is easy. 
Since settings have moved, in a potentially backwards incompatible way, there may need to be a transition guide with the release explaining what to do. We may need to also bump the minor version to indicate the breaking changes.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Additional context:

> Part of the cleanup epic ✨

- [x] https://github.com/ynput/ayon-maya/pull/28
- [x] https://github.com/ynput/ayon-houdini/pull/47
- [x] https://github.com/ynput/ayon-blender/pull/11
- [x] https://github.com/ynput/ayon-resolve/pull/10
- [x] https://github.com/ynput/ayon-fusion/pull/6
- [x] https://github.com/ynput/ayon-substance-painter/pull/3
- [x] https://github.com/ynput/ayon-3dsmax/pull/7
- [x] https://github.com/ynput/ayon-harmony/pull/4
- [x] https://github.com/ynput/ayon-aftereffects/pull/7
- [x] https://github.com/ynput/ayon-photoshop/pull/7
- [x] https://github.com/ynput/ayon-tvpaint/pull/1
- [x] https://github.com/ynput/ayon-openrv/pull/14
- [x] https://github.com/ynput/ayon-celaction/pull/1
- [x] https://github.com/ynput/ayon-nuke/pull/7
- [x] https://github.com/ynput/ayon-hiero/pull/3
- [x] https://github.com/ynput/ayon-flame/pull/1
- [x] https://github.com/ynput/ayon-traypublisher/pull/4

**Comment by BigRoy** [comment]
Oops - can we link multiple PRs but have this only close if ALL of them are merged? If not, I may need to unlink them and just keep them in the PR description. @dee-ynput do you know?

**Comment by dee-ynput** [comment]
AFAIK closing one will always close the issue :'(

Mentioning them in the issue body is better in this case (and probably most cases)

I hope GH will change that someday  ✨

**Comment by BigRoy** [comment]
@dee-ynput all the listed integrations are now merged - I'll close this one.
