### ISSUE TITLE
General: Unify profile filter criteria in code

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#827]
**Description**

Profile filtering is done in a myriad of locations in the code and in some areas I think can be unified to avoid logic differences and errors.

As an example:

- In [`subset_name_profiles`](https://github.com/pypeclub/OpenPype/blob/b3391ebe7151ae540dc01201d43cf75651cd7979/openpype/lib/plugin_tools.py#L71-L91) the last part of the family name is used.
- In the current integrator (before refactor) [the full family name is used](https://github.com/pypeclub/OpenPype/blob/develop/openpype/plugins/publish/integrate_new.py#L835-L840) - same as in [Collect Ftrack Family](https://github.com/pypeclub/OpenPype/blob/4306a618a021ec8a4a66054e66ad4fca694b139a/openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py#L40)
- The [Collect Ftrack Family plug-in uses `api.Session["AVALON_APP"]`](https://github.com/pypeclub/OpenPype/blob/4306a618a021ec8a4a66054e66ad4fca694b139a/openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py#L39) for the `hosts` filter criteria whereas the [Integrator uses `context.data["host_name"]`](https://github.com/pypeclub/OpenPype/blob/e80f0d18d27183dbbc67e8acaa89b6cde9caf80e/openpype/plugins/publish/integrate_new.py#L837) 
- The filter criteria also came up on [this PR](https://github.com/pypeclub/OpenPype/pull/2969#discussion_r838257439) just now which recommends using `context.data["hostName"]` which however CAN be different from `api.Session["AVALON_APP"]` which as listed above is potentially also wrongly used in some areas of the code?
- The [Collect Ftrack Family plug-in](https://github.com/pypeclub/OpenPype/blob/4306a618a021ec8a4a66054e66ad4fca694b139a/openpype/modules/ftrack/plugins/publish/collect_ftrack_family.py#L42-L46) filter criteria doesn't expose the `task_type` entry in the filter criteria even though the Admin settings does expose it. This seems like a **bug** which I think can be traced back to not having a clear definition and entry point for these filter criteria.

I'm aware the `filter_profiles` is also used in other ways with other filter criteria. However it seems like a bunch of areas use the same filter criteria but seemingly with little consistency? At this point in time I'm mostly targeting those filtering criteria using

Even better if we could also unify this in Admin Settings with its own Profile Filter Schema for the settings - so that if we change the schema and the function all areas support the extra filtering features, like how it appears "Task Type" was added at a later state but not correctly implemented in some areas?

**Describe the solution you'd like**

Preferably expose a `get_profile_filter_criteria` method that clearly describes what it expects as input values. Or find another way to ease profile filtering in the many different locations in the code base.

In the Integrator Refactor I tried to use the simplest data source that is accessible that had the 'right' formatting compared to what the old integrator was doing and [turn that into `get_profile_filter_criteria` and made it use only the parsed `anatomyData`](https://github.com/pypeclub/OpenPype/pull/2898/files#diff-d4b836839eaaa5d85e220403cb758d98f0769ba8220488c424be668fc681defbR78-R94). Not saying that's the **good way** and I'd definitely love to include that in this Issue/discussion.

Additionally I think we can get by by having a single `collect_profile_filter_criteria` Collector so that other plug-ins could even use the cached `instance.data["profile_filter_criteria"]` or alike. Not sure if better but at least it'd mean consistent across the publishing workflow.

Nonetheless I feel the urge to just have an easily accessible and consistent way to create the filter criteria would be beneficial.

[cuID:[OP-2989](https://app.clickup.com/t/25em4g4)]

**Comment by BigRoy** [comment]
Not sure how much is still problematic in AYON - but will transfer it to discuss.

**Comment by iLLiCiTiT** [comment]
My personal opinion is that DRY can hurt sometimes, especially when we did split addons. I would say it is much safer and better to create the data at the place where is used instead of trying to abstract it.

**Comment by iLLiCiTiT** [comment]
Seems like you agreed with my previous opinion? Closing issue, please reopen if you think it still should be resolved.
