### ISSUE TITLE
Modules: Allow modules to be customized per project

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#829]
**Is your feature request related to a problem? Please describe.**

Currently we have settings for the Modules that are system wide, like Ftrack URL and whether Ftrack is enabled or not. However, we are running into the cases where one project might use Ftrack - another might not at all. One project might run one Ftrack url, another might need another.

Would it be possible to implement some (or all?) modules in such a way that they could be project-specific? Or in such a way that'd be trivial for each module to define "project specific settings"?

**Describe the solution you'd like**

Allow to enable/disable full modules like Ftrack (and upcoming Shotgun, Ftrack, etc.) 

**Describe alternatives you've considered**

For e.g. ftrack it could currently be possible to disable all publish plug-ins in project settings to "reduce" relying on Ftrack but it's been not clearly documented and I believe for a large part untested. Instead we need an approach that from the ground up could allow to enable/disable whether a project runs with Ftrack or Shotgun, and if they do - with which url, etc.

[cuID:[OP-5536](https://app.clickup.com/t/861mm69nr)]

**Comment by BigRoy** [comment]
Still relevant to AYON - but not sure if we want to track on ayon-core. Will let @dee-ynput and @mkolar decide how to push this forward?

**Comment by iLLiCiTiT** [comment]
Closing this issue for now. It is still relevant, but at this moment ayon-core is not first class citizen.
