### ISSUE TITLE
Manager: Filter to outdated toggle does not work

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When **Filter to outdated** is enabled no filtering occurs.

![filter_to_outdated](https://github.com/user-attachments/assets/c936c0a3-1740-48d3-aeb9-63e98cd53590)

Reproduced in Maya 2024.2 and Fusion 18 - so I suppose issue is in core.
There is no logged error.

### Expected Behavior:

Only the "red versioned" entries should remain listed with the filter enabled.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load multiple versions
2. Enable "Filter to outdated"

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by LiborBatek** [comment]
Quite important to fix it...yet over month without any progress @iLLiCiTiT
