### ISSUE TITLE
Launcher Explore Icon is not working

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-core#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

https://gyazo.com/dca48f74171699ad4f428a56a72667cd

Explore Icon is showing an error

### Expected Behavior:

When clicked it should open the explorer in windows 10

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

In the launcher choose any task and hit explore at the bottom pane

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
@krishnaavril I have a feeling this is also due to something with that Priority attribute you had and the issue with your server update to 1.5.0 that now brought its own priority attribute to the table?

**Comment by krishnaavril** [comment]
Yes it is the priority attribute, it's not a bug, sorry and thanks
Working fine in 1.4.2
