### ISSUE TITLE
Load and manage products from a library project

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-core#983]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

The loader is currently able to load products from another (library) project. However, those have traditionally **never** been able to remain 'managed' and updated.

I'd like to propose a means to allow loading from another project and keep the full management working by persisting the `product_name` with the container data.

### How would you imagine the implementation of the feature?

Upon loading, we also imprint the loaded container with the `project_name` data alongside the representation id.

That way, anything that takes the `container` like `update_container` to set versions or alike is capable of also using the project name data to update correctly to a new version. Due to that we don't need to customize the function signature for `update_container`

There will be some more we'll need to do:

Required:

- Loaders will need to be able to imprint the `project_name` data.
- The `Loader.filepath_from_context` method should be tested with it's correctly resolving for another context than the current project.
- The Scene Inventory (manager) UI should be capable of also listing containers with this `project_name` metadata and also query the data/info regarding the other project.

Not critical for MVP:

- The "Switch Asset" UI may need to also support the `project_name` to allow switching these containers from another project too.
- The "Collect Scene Inputs" and [their input versions](https://github.com/ynput/ayon-core/blob/f54ff5622e8e5e00de3531a71006c224cd30c001/client/ayon_core/plugins/publish/collect_input_representations_to_versions.py#L6-L59) are collected solely using representation id for "links". To make that work correctly it _may_ need to also allow representation ids NOT part of the current project also with this `project_name` data attached to it to correctly identify it.

### Are there any labels you wish to add?

- [x] I have added the relevant labels to the enhancement request.

**Comment by moonyuet** [comment]
I studied a little bit with the code. The issue possibly contributes to the following function can't manage to find versions and the name of the project as we can always stick with searching the representation and version through the current project name. 
https://github.com/ynput/ayon-core/blob/4b5573d0a4ca1bc738ea55bfe451e5ee2a01e826/client/ayon_core/tools/sceneinventory/models/containers.py#L222-L243

https://github.com/ynput/ayon-core/blob/4b5573d0a4ca1bc738ea55bfe451e5ee2a01e826/client/ayon_core/tools/sceneinventory/models/containers.py#L297-L307
